#AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"test": "00_core.ipynb",
         "hhhhhe": "00_core.ipynb"}

modules = ["nv_test.py"]

git_url = "https://github.com/fastai/nbdev_eda/tree/master/"

def custom_doc_links(name): return None